### ISSUE TITLE
Quick Fix: Extra Word '...on' 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/responsive-layout#7]
Line 4 "...would look like the following ON WHEN following" has extra "on".  See lesson text below. 

*************
Using the Mobile Up (Mobile First) Strategy with Wrappers
In the opposite direction, a design concept that is becoming more and more prevalent is making a website for the smaller screen first, then adding in media queries to handle larger and larger screen sizes. The previous example, reversed, would look like the following on when following the mobile up design pattern.

**Comment by jenmyers** [comment]
Resolved.
